---
- name: Install core packages
  become: true
  community.general.zypper:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Locate the zsh shell
  ansible.builtin.shell: command -v zsh
  register: zsh_path
  ignore_errors: true

- name: Change the default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
  when: zsh_path.rc == 0 and zsh_path.stdout != ''
  ignore_errors: true
