local opt = vim.opt
local g = vim.g

-- Skip ts_context_commentstring module to speed up loading
g.skip_ts_context_commentstring_module = true
opt.autowrite = true -- Enable auto write
opt.autoread = true -- Enable autoread
opt.clipboard = "unnamedplus" -- Sync with system clipboard
opt.completeopt = "menu,menuone,noselect"
opt.conceallevel = 3 -- Hide * markup for bold and italic
opt.cursorline = true -- Enable highlighting of the current line
opt.expandtab = true -- Use spaces instead of tabs
opt.formatoptions = "jcroqlnt" -- tcqj
opt.grepprg = "rg --vimgrep --smart-case --follow"
opt.ignorecase = true -- Ignore case
opt.inccommand = "nosplit" -- preview incremental substitute
opt.incsearch = true
opt.list = true -- Show some invisible characters (tabs...
opt.mouse = "a" -- Enable mouse mode
opt.number = false -- Print line number
opt.laststatus = 3
opt.pumblend = 10 -- Popup blend
opt.pumheight = 10 -- Maximum number of entries in a popup
opt.relativenumber = true -- Relative line numbers
opt.scrolloff = 5 -- Lines of context
opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
opt.shiftround = true -- Round indent
opt.shiftwidth = 2 -- Size of an indent
opt.shortmess:append { W = true, I = true, c = true }
opt.showmode = false -- Dont show mode since we have a statusline
opt.sidescrolloff = 8 -- Columns of context
opt.signcolumn = "yes" -- Always show the signcolumn, otherwise it would shift the text each time
opt.smartcase = true -- Don't ignore case with capitals
opt.smartindent = true -- Insert indents automatically
opt.spelllang = { "en" }
opt.splitbelow = true -- Put new windows below current
opt.splitright = true -- Put new windows right of current
opt.tabstop = 2 -- Number of spaces tabs count for
opt.termguicolors = true-- True color support
opt.timeoutlen = 300 -- Increased for better which-key usage and to avoid accidental key triggers
opt.swapfile = false -- No swap file
opt.backup = false -- no backup file
opt.undofile = true
opt.undolevels = 20000
opt.updatetime = 200
opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
opt.wildmode = "longest:full,full" -- Command-line completion mode
opt.winminwidth = 5 -- Minimum window width
opt.wrap = true -- Enable line wrap
opt.shell = "/bin/fish" -- Set shell
opt.title = true -- Set title
opt.ff = "unix" -- Fileformat
opt.fileencoding = "utf8" -- Set utf8
