#!/bin/bash
set -eu

confirm() {
  cmd=("$@")
  read -r choice
  if echo "${choice}" | grep -Eq '^[Yy]?$'; then
    "${cmd[@]}"
  fi
}

shell_base() {
  printf 'Checkout private Fonts? [Y/n] '
  confirm git submodule update --init --recursive fonts
  printf 'Install Fish Plugin Manager? [Y/n] '
  confirm ./installation/fish_plugin_manager.sh
  printf 'Install Tmux Plugin Manager? [Y/n] '
  confirm ./installation/tmux_plugin_manager.sh
  printf 'Install Dotfiles? [Y/n] '
  confirm ./install
}

printf 'Install Base Packages? [Y/n] '
confirm ./installation/base_install.sh

shell_base

printf 'Install Brave? [Y/n] '
confirm ./installation/brave_install.sh

printf 'Install Chrome? [Y/n] '
confirm ./installation/chrome_install.sh
