#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
BOOTSTRAP_CONFIG="bootstrap.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_PLUGIN_DIR="plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

if [ "$1" == "bootstrap" ]; then
    CONFIG="$BOOTSTRAP_CONFIG"
    shift
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir $DOTBOT_PLUGIN_DIR -c "${CONFIG}" "${@}"
