#!/bin/bash
export ANSIBLE_NOCOWS=1
export ANSIBLE_RETRY_FILES_ENABLED=false
export ANSIBLE_INTERPRETER_PYTHON=auto_silent
PLAYBOOK=ansible/install.yml

if [ -n "$CI" ]; then
  ansible-playbook -i localhost, -c local "$PLAYBOOK"
else
  ansible-playbook -i localhost, -c local "$PLAYBOOK" --ask-become-pass
fi
