---
- name: Install fonts
  become: true
  community.general.zypper: 
    name: "{{ item }}"
    state: present
  loop: "{{ fonts }}"

- name: Ensure fonts submodule is updated
  ansible.builtin.git:
    repo: 'git@github.com:Saulimedes/fonts.git'
    dest: '{{ playbook_dir }}/fonts'
    recursive: true
    force: true
    accept_hostkey: true
  ignore_errors: true
  register: fonts_submodule_update

- name: Ensure .local/share/fonts directory exists in the home directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755' 

- name: Symlink fonts
  ansible.builtin.shell: stow --adopt -d . -t ~/.local/share/fonts/ fonts
  when: fonts_submodule_update is not failed
  tags: 
    - dotfiles

- name: Install desktop packages
  become: true
  community.general.zypper: 
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Symlink desktop dotfiles
  ansible.builtin.shell: stow --adopt -d config -t ~/ {{ item }}
  loop:
    - yt-dlp
    - mpv
  tags: 
    - dotfiles

- name: Create a containers directory in the current user's .config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers"
    state: directory
    mode: '0755'
    
- name: Copy registries.conf to the new containers directory
  ansible.builtin.copy:
    src: /etc/containers/registries.conf
    dest: "{{ ansible_env.HOME }}/.config/containers/registries.conf"
    remote_src: yes
    mode: '0644'
    owner: "{{ ansible_user_id }}"
  notify: Update registries.conf

- name: Add current user to the flatpak group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: flatpak
    append: yes

- name: Add the Flathub repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak }}"

