pinentry-program /usr/bin/pinentry-emacs
allow-emacs-pinentry
pinentry-timeout 36000
allow-loopback-pinentry
enable-ssh-support
default-cache-ttl-ssh 61200
max-cache-ttl-ssh 61200
default-cache-ttl 61200
max-cache-ttl 61200
