---
packages:
  - git
  - stow
  - bottom
  - socat
  - bat
  - bat-extras
  - direnv
  - ansible
  - ripgrep
  - gzip
  - pyenv
  - 7zip
  - macchina
  - gzip
  - fzf
  - fzf-fish-completion
  - fzf-bash-completion
  - fzf-tmux
  - fd
  - ansible-lint
  - tealdeer
  - lsd
  - strace
  - sshpass
  - fish
  - zip
  - unrar
  - btop
  - ShellCheck
  - pwgen
  - gcc
  - make
  - openssl
  - tcpdump
  - nmap
  - zoxide
  - jq
  - yq
  - yq-fish-completion
  - telnet
  - net-tools
  - gcc-c++
  - bind-utils
  - starship
  - netcat-openbsd
  - hyperfine
  - nodejs
  - httpie
  - curl
  - pandoc
  - tmux
  - yazi

fish_plugins:
  - jorgebucaran/fisher
  - edc/bass
  - evanlucas/fish-kubectl-completions
  - kidonng/zoxide.fish
  - jorgebucaran/autopair.fish
