---
- name: Install emacs
  become: true
  community.general.zypper: 
    name: emacs
    state: present

- name: Symlink emacs config
  ansible.builtin.shell: stow --adopt -d config -t ~/ emacs
  tags: 
    - dotfiles
