---
- name: Import LibreWolf GPG key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.librewolf.net/pubkey.gpg

- name: Add the LibreWolf repository
  become: true
  community.general.zypper_repository:
    name: librewolf
    repo: https://rpm.librewolf.net
    auto_import_keys: true
    state: present

- name: Install LibreWolf
  become: true
  community.general.zypper: 
    name: librewolf
    state: present

- name: Uninstall firefox if installed
  become: true
  community.general.zypper: 
    name: firefox
    state: absent

- name: Check for the existence of profiles.ini
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.librewolf/profiles.ini"
  register: profiles_ini_stat

- name: Start Librewolf to generate profiles.ini if not exists
  ansible.builtin.shell:
    cmd: "librewolf --headless"
  changed_when: false
  async: 25 
  poll: 0
  when: not profiles_ini_stat.stat.exists

- name: Wait a few seconds for Librewolf to initialize
  ansible.builtin.pause:
    seconds: 25
  when: not profiles_ini_stat.stat.exists

- name: Kill Librewolf after initialization
  ansible.builtin.shell:
    cmd: pkill -f librewolf
  changed_when: false
  when: not profiles_ini_stat.stat.exists

- name: Verify the contents of profiles.ini
  ansible.builtin.shell:
    cmd: cat "{{ ansible_env.HOME }}/.librewolf/profiles.ini"
  register: profiles_ini_contents
  changed_when: false

- name: Extract path of the default profile from profiles.ini
  ansible.builtin.shell:
    cmd: awk -F= '/Path=/ && f{print $2; exit} /Default=1/{f=1}' "{{ ansible_env.HOME }}/.librewolf/profiles.ini"
  register: librewolf_default_profile_path_raw
  changed_when: false

- name: Debug contents of profiles.ini
  ansible.builtin.debug:
    msg: "{{ profiles_ini_contents.stdout }}"

- name: Set librewolf default profile path as fact
  ansible.builtin.set_fact:
    librewolf_default_profile_path: "{{ ansible_env.HOME }}/.librewolf/{{ librewolf_default_profile_path_raw.stdout }}"
  when: librewolf_default_profile_path_raw.stdout | length > 0

- name: Debug extracted path
  ansible.builtin.debug:
    var: librewolf_default_profile_path_raw.stdout

- name: Add in Librewolf config
  ansible.builtin.copy:
    src: files/user.js
    dest: "{{ librewolf_default_profile_path }}/user.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0644'
  when: librewolf_default_profile_path is defined and librewolf_default_profile_path != ''

- name: Create chrome directory in Librewolf profile
  ansible.builtin.file:
    path: "{{ librewolf_default_profile_path }}/chrome"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0700'
  when: librewolf_default_profile_path is defined and librewolf_default_profile_path != ''

- name: Copy chrome directory content to Librewolf profile
  ansible.builtin.copy:
    src: files/chrome/
    dest: "{{ librewolf_default_profile_path }}/chrome"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0644'
  when: librewolf_default_profile_path is defined and librewolf_default_profile_path != ''

