#!/bin/sh
for arg in "$@"; do
  if [ -f "${arg}" ] ; then
      case "${arg}" in
        *.tar.bz2)   tar -xvf "${arg}"     ;;
        *.tar.gz)    tar -xvzf "${arg}"    ;;
        *.tar.xz|*.txz) tar -xvJf "${arg}"  ;;
        *.lzma)      unlzma "${arg}"        ;;
        *.bz2)       bunzip2 "${arg}"       ;;
        *.rar)       unrar x -ad "${arg}"   ;;
        *.gz)        gunzip "${arg}"        ;;
        *.tar)       tar -xvf "${arg}"      ;;
        *.tbz2)      tar -xvjf "${arg}"     ;;
        *.tgz)       tar -xvzf "${arg}"     ;;
        *.zip)       unzip "${arg}"         ;;
        *.Z)         uncompress "${arg}"    ;;
        *.7z)        7z x "${arg}"          ;;
        *.xz)        unxz "${arg}"          ;;
        *.exe)       cabextract "${arg}"    ;;
        *.deb)       mkdir -p "$extract_dir/control"
                      mkdir -p "$extract_dir/data"
                      cd "$extract_dir"
                      ar vx "../${arg}" > /dev/null
                      cd control
                      tar xzvf ../control.tar.gz
                      cd ../data
                      extract ../data.tar.*
                      cd ..
                      rm *.tar.* debian-binary
                      cd .. ;;
        *)           echo "extract: '${arg}' - unknown archive method" ;;
      esac
  else
      echo "Error: "${arg}" - file does not exist"
      exit 1
  fi
done

