#!/bin/bash
BRANCH="${1}"
ROOT="${2-main}"

if [ -z "$BRANCH" ] || [ "${BRANCH}" == "$(git branch --show-current)" ]; then
  git branch -a
elif [ $(git branch --list "${BRANCH}" --format='%(refname:short)') ]; then
  git switch "${BRANCH}"
else
 git checkout -b "${BRANCH}" "${ROOT}"
 git config branch."${BRANCH}".localmerge "${ROOT}"
fi
