require("plugins.alpha")
require("plugins.autopairs")
require("plugins.hop")
require("plugins.identline")
require ("plugins.nvimtree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.git")
require("plugins.toggleterm")
require("plugins.telescope")
require("plugins.undotree")
require("plugins.whichkey")
