---
packages:
  - kubectx
  - kubernetes-client
  - git-crypt
  - opentofu
  - stern
  - kubens
  - k9s
  - kustomize
  - helm
  - popeye
  - kubesec
  - kubie
  - clang
  - ollama
  - cilium-cli
  - taskwarrior
