---
name: lint and bootstrap

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: opensuse/tumbleweed

    steps:
      - uses: actions/checkout@v2
        name: Check out repository code

      - name: Install Ansible and ansible-lint
        run: |
          zypper install -y ansible ansible-lint
          echo "root ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/github-actions
          chmod 0440 /etc/sudoers.d/github-actions

      - name: Run ansible-lint
        run: ansible-lint

      - name: Execute bootstrap script
        run: ansible-playbook install.yml 

